/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

import com.gvillena.MainForm;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author alumno
 */
public class Modulo_de_Pago extends javax.swing.JFrame {
    
    String ttarjeta = "";
    String dfecha = "";
    String mfecha = "";
    
    String titular="",tarjeta="",codseguridad="",caducidad="",precio="";
   BufferedWriter bw ;
    PrintWriter pw;
    FileWriter fw;
    File f; 
    
    JSONObject obj = new JSONObject();
    JSONArray list = new JSONArray();
    
    private String cadena;

    /**
     * Creates new form Modulo_de_Pago
     */
    public Modulo_de_Pago() {
        this.cadena = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLTiendaClaro = new javax.swing.JLabel();
        jTFEquipo = new javax.swing.JPanel();
        jLTipoTarjeta = new javax.swing.JLabel();
        jBTTarjeta = new javax.swing.JComboBox();
        jLNumeroTarjeta = new javax.swing.JLabel();
        jTFNumeroTarjeta = new javax.swing.JTextField();
        jLCodigoSeguridad = new javax.swing.JLabel();
        jLFechaCaducidad = new javax.swing.JLabel();
        jCBFechaCaducidad1 = new javax.swing.JComboBox();
        jCBFechaCaducidad2 = new javax.swing.JComboBox();
        jLDsipositivo = new javax.swing.JLabel();
        jLPlan = new javax.swing.JLabel();
        jLImporteTotal = new javax.swing.JLabel();
        jTFCodigoSeguridad = new javax.swing.JPasswordField();
        jTFImporteTotal1 = new javax.swing.JLabel();
        jTFEquipos = new javax.swing.JLabel();
        jTFPlan = new javax.swing.JLabel();
        jPComprar = new javax.swing.JPanel();
        jBComprarFinal = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jRBTerminosyCondiciones = new javax.swing.JRadioButton();
        imgTarjetas = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTiendaClaro.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLTiendaClaro.setText("Modulo de Pago");

        jLTipoTarjeta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLTipoTarjeta.setText("Tipo de Tarjeta");
        jLTipoTarjeta.setPreferredSize(new java.awt.Dimension(120, 25));

        jBTTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Master Card", "American Express", " " }));
        jBTTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTTarjetaActionPerformed(evt);
            }
        });

        jLNumeroTarjeta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLNumeroTarjeta.setText("Numero de Tarjeta");
        jLNumeroTarjeta.setPreferredSize(new java.awt.Dimension(25, 120));

        jTFNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroTarjetaActionPerformed(evt);
            }
        });

        jLCodigoSeguridad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLCodigoSeguridad.setText("Codigo de Seguridad");
        jLCodigoSeguridad.setPreferredSize(new java.awt.Dimension(120, 25));

        jLFechaCaducidad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLFechaCaducidad.setText("Fecha de Caducidad");

        jCBFechaCaducidad1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCBFechaCaducidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFechaCaducidad1ActionPerformed(evt);
            }
        });

        jCBFechaCaducidad2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jCBFechaCaducidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFechaCaducidad2ActionPerformed(evt);
            }
        });

        jLDsipositivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLDsipositivo.setText("Dispositivo");

        jLPlan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLPlan.setText("Plan de Compra");

        jLImporteTotal.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLImporteTotal.setText("Importe Total");

        jTFCodigoSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoSeguridadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTFEquipoLayout = new javax.swing.GroupLayout(jTFEquipo);
        jTFEquipo.setLayout(jTFEquipoLayout);
        jTFEquipoLayout.setHorizontalGroup(
            jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTFEquipoLayout.createSequentialGroup()
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigoSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jTFEquipoLayout.createSequentialGroup()
                                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLPlan)
                                    .addComponent(jLTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 132, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addComponent(jLNumeroTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addComponent(jLDsipositivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addComponent(jCBFechaCaducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBFechaCaducidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFCodigoSeguridad)
                    .addComponent(jTFNumeroTarjeta)
                    .addComponent(jBTTarjeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(jTFEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTFImporteTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTFEquipoLayout.setVerticalGroup(
            jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTFEquipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBTTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBFechaCaducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBFechaCaducidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jTFEquipoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDsipositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jTFEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFImporteTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBComprarFinal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jBComprarFinal.setText("! COMPRAR !");
        jBComprarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComprarFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPComprarLayout = new javax.swing.GroupLayout(jPComprar);
        jPComprar.setLayout(jPComprarLayout);
        jPComprarLayout.setHorizontalGroup(
            jPComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComprarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jBComprarFinal)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPComprarLayout.setVerticalGroup(
            jPComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComprarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBComprarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jBAtras.setText("ATRAS");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jRBTerminosyCondiciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRBTerminosyCondiciones.setText("Acepto Terminos y Condiciones");
        jRBTerminosyCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTerminosyCondicionesActionPerformed(evt);
            }
        });

        imgTarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jBAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jTFEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLTiendaClaro)
                            .addGap(91, 91, 91)
                            .addComponent(imgTarjetas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jRBTerminosyCondiciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTiendaClaro)
                    .addComponent(imgTarjetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jRBTerminosyCondiciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBTerminosyCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTerminosyCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBTerminosyCondicionesActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        MainForm main = new MainForm();
        main. setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jBComprarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComprarFinalActionPerformed
        
        try {
            guargarVenta();
            JOptionPane.showMessageDialog(null,"Gracias por su compra");
          
        } catch (IOException ex) {
              
          }
       

        
    }//GEN-LAST:event_jBComprarFinalActionPerformed

    private void jCBFechaCaducidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFechaCaducidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFechaCaducidad2ActionPerformed

    private void jTFNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroTarjetaActionPerformed

    private void jBTTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTTarjetaActionPerformed

    private void jTFCodigoSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoSeguridadActionPerformed

    private void jCBFechaCaducidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFechaCaducidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFechaCaducidad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_de_Pago().setVisible(true);
            }
        });
    }
    
    public void guargarVenta()throws IOException{
        ttarjeta=jBTTarjeta.getSelectedItem().toString();
        dfecha = jCBFechaCaducidad1.getSelectedItem().toString();
        mfecha=jCBFechaCaducidad1.getSelectedItem().toString();
        
        
     f= new File("D:\\RegistrodeVentas.txt");  
      obj.put("","Christian Ferrua");
      obj.put("","");
      obj.put("TIENDA", "CLARO Perú");
      JSONObject objc = new JSONObject();
      obj.put("FACTURA",objc );
      objc.put("Dispositivo ", jTFEquipos.getText());
      objc.put("Plan ", jTFPlan.getText());
      objc.put("Importe ", jTFImporteTotal1.getText());
      objc.put("Tipo de Tarjeta ", ttarjeta);
      objc.put("Numero de Tarjeta ", jTFNumeroTarjeta.getText());
      objc.put("Cod. Tarjeta",jTFCodigoSeguridad.getText());
      objc.put("Fecha de Caducidad de Tarjeta", dfecha+"/"+mfecha);
      
      fw= new FileWriter("D:\\RegistrodeVentas.txt");
      fw.write(obj.toJSONString());
      fw.flush();
      fw.close();
    }

    
    /*public void guardasVenta(){
        try{
            FileWrite fw = new FileWrite("Venta.txt",true);
            BufferedWrite
            
        }catch(Exception e){
    }*/
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgTarjetas;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBComprarFinal;
    private javax.swing.JComboBox jBTTarjeta;
    private javax.swing.JComboBox jCBFechaCaducidad1;
    private javax.swing.JComboBox jCBFechaCaducidad2;
    private javax.swing.JLabel jLCodigoSeguridad;
    private javax.swing.JLabel jLDsipositivo;
    private javax.swing.JLabel jLFechaCaducidad;
    private javax.swing.JLabel jLImporteTotal;
    private javax.swing.JLabel jLNumeroTarjeta;
    private javax.swing.JLabel jLPlan;
    private javax.swing.JLabel jLTiendaClaro;
    private javax.swing.JLabel jLTipoTarjeta;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPComprar;
    private javax.swing.JRadioButton jRBTerminosyCondiciones;
    private javax.swing.JPasswordField jTFCodigoSeguridad;
    private javax.swing.JPanel jTFEquipo;
    public static javax.swing.JLabel jTFEquipos;
    public static javax.swing.JLabel jTFImporteTotal1;
    private javax.swing.JTextField jTFNumeroTarjeta;
    public static javax.swing.JLabel jTFPlan;
    // End of variables declaration//GEN-END:variables
}
